import Head from 'next/head';

const Layout = ({children, title}) => {
    return (
        <>
        <Head>
            <title>{title}</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
        </Head>
       
       {children}
     
      <footer className='h-48 text-center text-3xl  bg-black text-white'>
        <h1 className='text-4xl justify-around py-11'>Contace me</h1>
        pubudu,lackmlca@gamil.com
      </footer>
        </>
    )
}

export default Layout;